instaclone/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow', views.follow, name='follow'),
    path('<username>/follow_list/', views.follow_list, name='follow_list'),
]

instaclone/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<article_pk>/', views.detail, name='detail'),
    path('<article_pk>/update/', views.update, name='update'),
    path('<article_pk>/delete/', views.delete, name='delete'),
    path('<article_pk>/comments_create', views.comments_create, name='comments_create'),
    path('<article_pk>/<comment_pk>/comments_delete', views.comments_delete, name='comments_delete'),
    path('<article_pk>/like/', views.like, name='like'),
    path('<article_pk>/like_list/', views.like_list, name='like_list'),

]

instaclone/instaclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instaclone/community/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    # 원본 그대로
    image = models.ImageField()
    # DB 저장 X, 호출하게되면, 잘라서 표현
    image_thumbnail = ImageSpecField(source='image',
                          processors=[Thumbnail(300, 300)],
                          format='JPEG',
                          options={'quality': 60})

    # 원본 잘라서 저장 : ProcessedImageField
    # image = ProcessedImageField(
    #                       processors=[ResizeToFill(100, 50)],
    #                       format='JPEG',
    #                       options={'quality': 60})

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_articles'
    )

class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

instaclone/community/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'
        exclude = ['created_at', 'updated_at', 'user', 'like_users',]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

instaclone/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .models import Article, Comment
from .forms import ArticleForm, CommentForm


def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'community/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('community:index')
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'community/form.html', context)



@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                article = form.save()
                return redirect('community:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
        context = {
            'form': form,
            'article': article,
        }
        return render(request, 'community/form.html', context)


@login_required
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        article.delete()
    return redirect('community:index')


def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment_form = CommentForm()
    context = {
        'article': article,
        'comment_form': comment_form,
    }
    return render(request, 'community/detail.html', context)

@require_POST
def comments_create(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
        return redirect('community:detail', article.pk)
    else:
        return redirect('accounts:login')

def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
        return redirect('community:detail', article.pk)
    else:
        return redirect('accounts:login')

@login_required
def like(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user
    if article.like_users.filter(id=user.pk).exists():
        article.like_users.remove(user)
    else:
        article.like_users.add(user)
    return redirect('community:detail', article.pk)

def like_list(request, article_pk):

    article = get_object_or_404(Article, pk=article_pk)
    l_list = article.like_users.all()
    context = {
        'article':article,
        'l_list':l_list,
    }
    return render(request, 'community/like_list.html', context)

instaclone/community/templates/community/_comments.html
<!--new comment-->
<form action="{% url 'community:comments_create' article.pk %}" method="POST">
    {% csrf_token %}
    <p>comment:<br>{{ comment_form.content }}</p>
    <input type="submit" value="write">
</form>

<!--comment list-->
{% for comment in article.comment_set.all %}
    <p>{{ comment.content }}</p>
    <form action="{% url 'community:comments_delete' article.pk comment.pk %}" method="POST">
    	{% csrf_token %}
    	<button>delete</button>
    </form>
{% endfor %}

instaclone/community/templates/community/_like.html
<!--likes : heart button-->
{% if request.user in article.like_users.all %}
    <a href="{% url 'community:like' article.pk %}">
        <i class="fas fa-heart text-danger"></i>
    </a>
{% else %}
    <a href="{% url 'community:like' article.pk %}">
        <i class="far fa-heart text-danger"></i>
    </a>
{% endif %}

<!--number of people who liked the post-->
{% if article.like_users.all|length > 1 %}
    <a href="{% url 'community:like_list' article.pk %}">{{ article.like_users.all|length }} likes</a>
{% else %}
    <a href="{% url 'community:like_list' article.pk %}">{{ article.like_users.all|length }} like</a>
{% endif %}
<hr>

instaclone/community/templates/community/detail.html
{% extends 'base.html' %}

{% block body %}
	<h2>DETAIL</h2>
	<hr>
	<a href="{% url 'accounts:profile' article.user %}">{{ article.user }}</a>
	<p>Title: {{ article.title }}</p>
	<p>Content: {{ article.content }}</p>
	<p>Created at: {{ article.created_at }}</p>
	<p>Updated at: {{ article.updated_at }}</p>
	<img src="{{ article.image_thumbnail.url }}">
	<br>
    {% if request.user == article.user %}
        <a href="{% url 'community:update' article.pk %}"><button>Edit</button></a>
        <a href="{% url 'community:delete' article.pk %}"><button>Delete</button></a><br>
    {% endif %}

    {% include 'community/_like.html' %}

    {% include 'community/_comments.html' %}

{% endblock %}

instaclone/community/templates/community/form.html
{% extends 'base.html' %}
{% block body %}
    {% if request.resolver_match.url_name == 'create' %}
    <h2>New Post</h2>
    <form action="{% url 'community:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Submit</button>
    </form>
    {% else %}
    <h2>Edit</h2>
        <form action="{% url 'community:update' article.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Update</button>
    </form>
    {% endif %}

{% endblock %}

instaclone/community/templates/community/index.html
{% extends 'base.html' %}
{% block body %}

<h2>Index</h2>
{% for article in articles %}
    <p><a href="{% url 'accounts:profile' article.user %}">{{ article.user }}</a>'s Post</p>
    <a href="{% url 'community:detail' article.pk %}">
        Title: {{ article.title }}
    </a>
    <br>
    <img src="{{ article.image_thumbnail.url }}">
    <br>

    {% include 'community/_like.html' %}

{% endfor %}

{% endblock %}

instaclone/community/templates/community/like_list.html
{% extends 'base.html' %}
{% block body %}

<h2>{{ article.user }}</h2>
{% for friend in l_list %}
    <a href="{% url 'accounts:profile' friend %}" class="my-3">{{ friend.username }}</a>

    <!--could follow or unfollow users from like list-->
    {% if friend == request.user %}
        <br>
    {% else %}
        {% if friend in request.user.followings.all %}
            <a href="{% url 'accounts:follow' friend.username %}" class="btn btn-sm btn-secondary my-3">unfollow</a>
            <br>

        {% else %}
            <a href="{% url 'accounts:follow' friend.username %}" class="btn btn-sm btn-primary my-3">follow</a>
            <br>
        {% endif %}
    {% endif %}
{% endfor %}

{% endblock %}