instaclone/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow', views.follow, name='follow'),
    path('<username>/follow_list/', views.follow_list, name='follow_list'),
]

instaclone/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<article_pk>/', views.detail, name='detail'),
    path('<article_pk>/update/', views.update, name='update'),
    path('<article_pk>/delete/', views.delete, name='delete'),
    path('<article_pk>/comments_create', views.comments_create, name='comments_create'),
    path('<article_pk>/<comment_pk>/comments_delete', views.comments_delete, name='comments_delete'),
    path('<article_pk>/like/', views.like, name='like'),
    path('<article_pk>/like_list/', views.like_list, name='like_list'),

]

instaclone/instaclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instaclone/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    followers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name = 'followings',
        )

instaclone/community/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    # 원본 그대로
    image = models.ImageField()
    # DB 저장 X, 호출하게되면, 잘라서 표현
    image_thumbnail = ImageSpecField(source='image',
                          processors=[Thumbnail(300, 300)],
                          format='JPEG',
                          options={'quality': 60})

    # 원본 잘라서 저장 : ProcessedImageField
    # image = ProcessedImageField(
    #                       processors=[ResizeToFill(100, 50)],
    #                       format='JPEG',
    #                       options={'quality': 60})

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_articles'
    )

class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

instaclone/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'username']

instaclone/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login, logout as auth_logout

from .forms import CustomUserCreationForm
from .models import User

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user= form.save()
            auth_login(request, user)
            return redirect('community:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/form.html', context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('community:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('community:index')

@login_required
def profile(request, username):
    User = get_user_model()
    user = get_object_or_404(User, username=username)
    context = {
        'user':user
    }
    return render(request, 'accounts/profile.html', context)

def follow(request, username):
    # bringing the data
    User = get_user_model()
    # the person getting followed
    user = get_object_or_404(User, username=username)
    # the owner of the profile => user
    # the person asking to follow => request.user
    if user != request.user:
        if user.followers.filter(username=request.user.username).exists():
            user.followers.remove(request.user)
        else:
            user.followers.add(request.user)
    return redirect('accounts:profile', user.username)

def follow_list(request, username):
    User = get_user_model()
    user = get_object_or_404(User, username=username)
    # GET method
    if request.GET.get('list') == 'followers':
        f_list = user.followers.all()
        follow_name = 'followers'
    elif request.GET.get('list') == 'followings':
        f_list = user.followings.all()
        follow_name = 'followings'
    context = {
        'user':user,
        'f_list':f_list,
    }
    return render(request, 'accounts/follow_list.html', context)

instaclone/accounts/templates/accounts/follow_list.html
{% extends 'base.html' %}
{% block body %}

<h2>{{ user }}</h2>
{% for friend in f_list %}
    <a href="{% url 'accounts:profile' friend %}" class="my-3">{{ friend.username }}</a>
    {% if friend == request.user %}
        <br>
    {% else %}
        {% if friend in request.user.followings.all %}
            <a href="{% url 'accounts:follow' friend.username %}" class="btn btn-sm btn-secondary my-3">unfollow</a>
            <br>
        {% else %}
            <a href="{% url 'accounts:follow' friend.username %}" class="btn btn-sm btn-primary my-3">follow</a>
            <br>
        {% endif %}
    {% endif %}
{% endfor %}
{% endblock %}

instaclone/accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% block body %}
    {% if request.resolver_match.url_name == 'signup' %}
    <h2>Sign Up</h2>
    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>submit</button>
    </form>
    {% else %}
    <h2>Login</h2>
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>submit</button>
    </form>
    {% endif %}
{% endblock %}

instaclone/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block body %}
<h2>{{ user.username }}'s Profile</h2>
<hr>
<!--Followers Followings-->
<!--if the profile page is someone else's -->
{% if user != request.user %}
    <!--if the user is already following the person-->
    {% if request.user in user.followers.all %}
        <a href="{% url 'accounts:follow' user.username %}" class="btn btn-sm btn-secondary">unfollow</a>
    <!--if the user is not following the person-->
    {% else %}
        <a href="{% url 'accounts:follow' user.username %}" class="btn btn-sm btn-primary">follow</a>
    {% endif %}
{% endif %}

<!--all posts and all likes-->
<p>All Posts | {{ user.article_set.all|length }} posts</p>
<a href="{% url 'accounts:follow_list' user.username %}?list=followers">followers {{ user.followers.all.count }}</a>
<br>
<a href="{% url 'accounts:follow_list' user.username %}?list=followings">followings {{ user.followings.all.count }}</a>
<hr>

<h3>Posts</h3>
{% for article in user.article_set.all %}
  <a href="{% url 'community:detail' article.pk %}">{{ article.title }}</a>
  <br>
  <img src="{{ article.image_thumbnail.url }}">
  <br>
{% endfor %}
<p>Total Likes | {{ user.like_articles.all|length }}</p>




{% endblock %}