moviereview/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

moviereview/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.review_list, name='review_list'),
    path('create/', views.create, name='create'),
    path('<review_pk>/', views.review_detail, name='review_detail'),
    path('<review_pk>/update', views.update, name='update'),
    path('<review_pk>/delete', views.delete, name='delete'),
    path('<review_pk>/comments', views.comments_create, name='comments_create'),
    path('<review_pk>/comments/<comment_pk>/delete', views.comments_delete, name='comments_delete'),
]

moviereview/moviereview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
]

moviereview/accounts/models.py
from django.db import models

# Create your models here.

moviereview/community/models.py
from django.db import models
from django.conf import settings

class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=30)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

moviereview/community/forms.py
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'movie_title', 'rank', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

moviereview/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required

def signup(request):
    if request.user.is_authenticated:
        return redirect('community:review_list')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('community:review_list')
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('community:review:list')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('community:review_list')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('community:review_list')

moviereview/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from .models import Review, Comment
from .forms import ReviewForm, CommentForm


def review_list(request):
    reviews = Review.objects.order_by('-pk')
    context = {'reviews':reviews}
    return render(request, 'community/review_list.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review = form.save()
            return redirect('community:review_detail', review.pk)
    else:
        form = ReviewForm()
    context = {
        'form': form
    }
    return render(request, 'community/form.html', context)

def review_detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm()
    context = {
        'review': review,
        'comment_form': comment_form,
    }
    return render(request, 'community/review_detail.html', context)

@login_required
def update(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user == review.user:
        if request.method == 'POST':
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                review = form.save()
                return redirect('community:review_detail', review.pk)
        else:
            form = ReviewForm(instance=review)
        context = {
            'form': form,
            'review': review,
        }
        return render(request, 'community/form.html', context)

@login_required
def delete(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user == review.user:
        review.delete()
    return redirect('community:review_list')

@require_POST
def comments_create(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.review = review
            comment.save()
        return redirect('community:review_detail', review.pk)
    else:
        return redirect('accounts:login')

def comments_delete(request, review_pk, comment_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
        return redirect('community:review_detail', review.pk)
    else:
        return redirect('accounts:login')

moviereview/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="LOGIN">
    </form>

{% endblock %}

moviereview/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="SIGN UP">
    </form>
{% endblock %}

moviereview/community/templates/community/form.html
{% extends 'base.html' %}
{% block body %}
    {% if request.resolver_match.url_name == 'create' %}
    <h1>New Post</h1>
    <form action="{% url 'community:create' %}" method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form>
    {% else %}
    <h1>Edit</h1>
    <form action="{% url 'community:update' review.pk %}" method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form>
    {% endif %}
{% endblock %}

moviereview/community/templates/community/review_detail.html
{% extends 'base.html' %}

{% block body %}
    <h2>{{ review.title }}</h2>
    <h3>{{ review.movie_title }}</h3>
    <p>{{ review.user.username }}</p>
    <p>created at: {{ review.created_at }}</p>
    <p>updated at: {{ review.updated_at }}</p>
    <hr>
    <p>{{ review.content }}</p>

    {% if review.user == request.user %}
        <a href="{% url 'community:update' review.pk %}"><button>Edit</button></a>
        <a href="{% url 'community:delete' review.pk %}"><button>Delete</button></a>
    {% endif %}

    <h3>Comments</h3>
    <ol>
    {% for comment in review.comment_set.all %}
        <li>{{ comment.content }}</li>
        <a href="{% url 'community:comments_delete' review.pk comment.pk %}">Delete</a>
    {% endfor %}
    </ol>

    <form action="{% url 'community:comments_create' review.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" value="submit">
    </form>
{% endblock %}

moviereview/community/templates/community/review_list.html
{% extends 'base.html' %}

{% block body %}
    <h1>Reviews</h1>
    {% for review in reviews %}
    <p>{{ review.pk }}</p>
    <h4>{{ review.title }}</h4>
    <a href="{% url 'community:review_detail' review.pk %}">Details</a>
    {% endfor %}
{% endblock %}

moviereview/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Movie Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'community:review_list' %}">Review</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'community:review_list' %}">Home</a>
          <a class="nav-item nav-link" href="{% url 'community:create' %}">New</a>
          {% if request.user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
          {% else %}
          <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
          <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>